// generated by tools/cursor-pipeline.py — do not edit
export const CURSORS = {
  "quill": {
    "src": "/cursors/quill.png",
    "w": 48,
    "h": 42,
    "hx": 0,
    "hy": 0,
    "pixel": false
  },
  "quill-hover": {
    "src": "/cursors/quill-hover.png",
    "w": 48,
    "h": 35,
    "hx": 4,
    "hy": 34,
    "pixel": false
  },
  "redpen": {
    "src": "/cursors/redpen.png",
    "w": 44,
    "h": 43,
    "hx": 0,
    "hy": 0,
    "pixel": false
  },
  "pixel-quill": {
    "src": "/cursors/pixel-quill.png",
    "w": 29,
    "h": 28,
    "hx": 0,
    "hy": 0,
    "pixel": true
  },
  "pixel-hand": {
    "src": "/cursors/pixel-hand.png",
    "w": 27,
    "h": 29,
    "hx": 0,
    "hy": 0,
    "pixel": true
  }
} as const;
